FROM registry.cn-hangzhou.aliyuncs.com/devflow/golang:1.25.8
WORKDIR /app
RUN apk add --no-cache git openssh-client ca-certificates
COPY .build/staging/_shared/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY .build/staging/devflow-config-service/devflow-config-service ./devflow-config-service
COPY .build/staging/devflow-config-service/docs ./docs
COPY .build/staging/devflow-config-service/config-repo ./config-repo
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
EXPOSE 8082
RUN adduser -D devuser
USER devuser
ENTRYPOINT ["/app/devflow-config-service"]
