FROM registry.cn-hangzhou.aliyuncs.com/devflow/ubuntu:v1
WORKDIR /app
COPY .build/staging/devflow-config-service/devflow-config-service ./devflow-config-service
COPY .build/staging/devflow-config-service/docs ./docs
COPY .build/staging/devflow-config-service/config-repo ./config-repo
EXPOSE 8082
ENTRYPOINT ["/app/devflow-config-service"]
