ALTER TABLE configurations
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS format TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS data TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS labels JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE workload_configs
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS exposed BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS labels JSONB NOT NULL DEFAULT '[]'::jsonb;
